from flask import Blueprint, Response
from ..services.auth import require_auth
from ..services.db import get_session
from ..services.models import Evidence
from sqlalchemy import func
import datetime

bp = Blueprint("reports_html", __name__)

@bp.get("/reports/roi/html")
@require_auth
def roi_html():
    s = get_session()
    if not s: return Response("DB disabled", status=400)
    mo = datetime.datetime.utcnow().strftime("%Y-%m")
    parts = dict(s.query(Evidence.category, func.sum(Evidence.amount_usd)).filter(Evidence.month==mo, Evidence.status=="protected").group_by(Evidence.category).all())
    total = float(sum(v or 0 for v in parts.values()))
    def fmt(n):
        try: return f"${{n:,.0f}}"
        except: return "$0"
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>ROI Report — {mo}</title>
<style>body{{font-family:-apple-system,Segoe UI,Roboto,Arial;background:#0f172a;color:#e5e7eb;padding:24px}}.card{{background:#111827;border-radius:12px;padding:16px;margin-bottom:16px}}</style>
</head><body>
<h1>Inventory Guardian — ROI Report</h1>
<div class="card"><h2>Protected this month</h2><div style="font-size:28px;font-weight:700">{fmt(total)}</div></div>
<div class="card"><h2>Breakdown</h2>
<ul>
  <li>Dead stock: {fmt(float(parts.get('dead_stock',0) or 0))}</li>
  <li>Stockouts avoided: {fmt(float(parts.get('stockout_risk',0) or 0))}</li>
  <li>Promo bleed: {fmt(float(parts.get('promo_bleed',0) or 0))}</li>
</ul>
</div>
<p style="opacity:.7">Generated by Inventory Guardian</p>
</body></html>"""
    return Response(html, mimetype="text/html")
